### ISSUE TITLE
A question about the paper

### ISSUE THREAD

**Issue by LangDaoAI** [Sahandfer/CEM#2]
Hi Sahand,

Just seeing your AAAA2022 pre-speaking and your paper,  and in my mind, COMET plays a critical role on generating cognitive empathy based on your paper.

Sure, I agree with you and commonsense reasoning is very very important for reaching human thinking.  My question is :  **whether having any 中文COMET  or  类似中文ATOMIC-2020 dataset for chineses empathy  dialog generating ?**

Thanks!

**Comment by Sahandfer** [comment]
Thank you for joining the talk. 
There was a paper submitted to the ACL Rolling Review (November 2021) called [C3KG: A Chinese Commonsense Conversation Knowledge Graph](https://openreview.net/forum?id=U9KwypIe7yU), which is essentially 中文ATOMIC. I think if this work gets good reviews and is published in ACL 2022, it is likely that there will be a 中文COMET.
